module.exports = {
    components: require('famous-components'),
    core: require('famous-core'),
    engine: require('famous-engine'),
    // domRenderers: require('famous-dom-renderers'),
    domRenderables: require('famous-dom-renderables'),
    layouts: require('famous-layouts'),
    // math: require('famous-math'),
    physics: require('famous-physics'),
    renderers: require('famous-renderers'),
    stylesheets: require('famous-stylesheets'),
    router: require('famous-router'),
    transitions: require('famous-transitions'),
    utilities: require('famous-utilities'),
    // webglRenderables: require('famous-webgl-renderables'),
    // webglRenderers: require('famous-webgl-renderers'),
    // webglGeometries: require('famous-webgl-geometries'),
    // webglMaterials: require('famous-webgl-materials'),
    // webglShaders: require('famous-webgl-shaders'),
    polyfills: require('famous-polyfills')
}
